import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class PdfService {
  static Future<void> generateAndPrintPdf(
    String diseaseName,
    Map<String, dynamic> resultData,
  ) async {
    final pdf = pw.Document();
    
    final riskLevel = resultData['risk_level'] ?? 'Unknown';
    final confidence = resultData['confidence_percentage']?.toDouble() ?? 0.0;
    final topFactors = resultData['top_factors'] as List<dynamic>? ?? [];
    final formattedDate = DateFormat('MMMM d, yyyy').format(DateTime.now());

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Medical AI Risk Assessment', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(formattedDate, style: const pw.TextStyle(fontSize: 14, color: PdfColors.grey700)),
                ],
              ),
              pw.Divider(thickness: 2),
              pw.SizedBox(height: 20),

              // Title
              pw.Text('Condition: $diseaseName', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 20),

              // Risk Summary Box
              pw.Container(
                padding: const pw.EdgeInsets.all(20),
                decoration: pw.BoxDecoration(
                  color: riskLevel.toLowerCase().contains('high') ? PdfColors.red50 : (riskLevel.toLowerCase().contains('medium') ? PdfColors.orange50 : PdfColors.green50),
                  border: pw.Border.all(color: PdfColors.grey300),
                  borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('Risk Level: ${riskLevel.toUpperCase()}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: riskLevel.toLowerCase().contains('high') ? PdfColors.red800 : PdfColors.black)),
                    pw.SizedBox(height: 10),
                    pw.Text('AI Confidence: ${confidence.toStringAsFixed(1)}%', style: const pw.TextStyle(fontSize: 14)),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),

              // SHAP Explanations
              pw.Text('Top Contributing Clinical Factors (SHAP Analysis)', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              
              pw.Table.fromTextArray(
                headers: ['Factor', 'Impact Score', 'Direction'],
                data: topFactors.map((factor) {
                  return [
                    factor['name'].toString(),
                    factor['impact'].toString(),
                    factor['direction'] == 'increasing' ? 'Increases Risk' : 'Decreases Risk',
                  ];
                }).toList(),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
                cellHeight: 30,
                cellAlignments: {
                  0: pw.Alignment.centerLeft,
                  1: pw.Alignment.center,
                  2: pw.Alignment.center,
                },
              ),

              pw.Spacer(),
              pw.Divider(),
              pw.Text('Disclaimer: This report is generated by an educational AI model and should not be used for definitive medical diagnosis.', 
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                textAlign: pw.TextAlign.center,
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: '${diseaseName.replaceAll(' ', '_')}_Report',
    );
  }
}
